.PHONY: all

DIRS = action_bars tools

# process all dirs specified above:
all:
	@ echo 'WARNING: Python libs are not yet included in Makefiles!'
	@ echo
	@ for i in $(DIRS); do make --directory $$i; done
