#!/usr/bin/python

"""
Process results of WingJ [1] with Imaris objects (exported from the statistics
part to XML) or ImageJ measurement results to do distance calculations.

[1] http://www.tschaffter.ch/
"""

from volpy.imagej import read_csv_com, WingJStructure
from log import log
import misc
import numpy as np
import imaris_xml as ix
import sys
import argparse


def wingj_dists_csv_export(files_wingj, files_out, calib=1.0,
        file_imsxml=None, file_ijroi=None):
    """Calculate distances from WingJ structures to spots in 2D.

    Takes a WingJStructure object plus a file with coordinates of points (can
    be either an XML file generated with Imaris containing a "Position" sheet
    or a CSV file generated by ImageJ containing "center of mass" coordinates)
    and calculates the closest distance from any point to each of the WingJ
    structures.

    Parameters
    ----------
    files_wingj, files_out : file handles or strings
        3-tuples of file handles or strings with filenames for the WingJ
        structure files resp. the corresponding output files.
    file_imsxml, file_ijroi : file handle or string
        A file handle or filename-string to an Imaris XML export resp. the
        ImageJ measurements CSV export.
    calib : float, optional
        The size of one pixel to correct WingJ coordinates with.

    Returns
    -------
    Nothing, all results are written to output CSV files directly.
    """
    if file_imsxml is not None:
        # create the ImarisXML object and read the 'Position' sheet
        coords = ix.ImarisXML(file_imsxml).coordinates_2d('Position')
    elif file_ijroi is not None:
        coords = read_csv_com(file_ijroi)
    else:
        raise AttributeError('no reference file given!')

    wingj = WingJStructure(files_wingj, calib)
    wingj.min_dist_csv_export(coords, files_out)

    log.info('Finished.')


def main():
    """Parse commandline arguments and run distance calculations."""
    argparser = argparse.ArgumentParser(description=__doc__)
    argparser.add_argument('--ap', required=True, type=file,
        help='WingJ structure file for the A-P separation.')
    argparser.add_argument('--vd', required=True, type=file,
        help='WingJ structure file for the V-D separation.')
    argparser.add_argument('--cnt', required=True, type=file,
        help='WingJ structure file for the contour line.')
    group = argparser.add_mutually_exclusive_group(required=True)
    group.add_argument('--imsxml', type=file, default=None,
        help='Imaris Excel XML export containing a "Position" sheet.')
    group.add_argument('--ijroi', type=file, default=None,
        help='ImageJ CSV export having "center of mass" measurements.')
    argparser.add_argument('--apout', type=argparse.FileType('w'),
        required=True, help='Output CSV file for distances to A-P line.')
    argparser.add_argument('--vdout', type=argparse.FileType('w'),
        required=True, help='Output CSV file for distances to V-D line.')
    argparser.add_argument('--cntout', type=argparse.FileType('w'),
        required=True, help='Output CSV file for distances to contour line.')
    argparser.add_argument('-p', '--pixelsize', required=False, type=float,
        default=1.0, help='Pixel size to calibrate WingJ data.')
    argparser.add_argument('-v', '--verbosity', dest='verbosity',
        action='count', default=0)
    try:
        args = argparser.parse_args()
    except IOError as err:
        argparser.error(str(err))

    misc.set_loglevel(args.verbosity)

    wingj_dists_csv_export(
        (args.ap, args.vd, args.cnt),
        (args.apout, args.vdout, args.cntout),
        args.pixelsize, args.imsxml, args.ijroi)


if __name__ == "__main__":
    sys.exit(main())
