#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.6.3 on Mon Oct 29 18:32:40 2012

import wx
from wx_filechooser import FileChooser
import wx.lib.filebrowsebutton as fbb

# begin wxGlade: extracode
# end wxGlade



class MyBaseFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        self.infile1 = ''
        self.infile1 = ''
        self.outfile1 = ''

        # begin wxGlade: MyBaseFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "File containing reference spots", style=wx.ALIGN_RIGHT)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.button_1 = wx.Button(self, -1, "Select")
        self.label_2 = wx.StaticText(self, -1, "File containing candidate spots", style=wx.ALIGN_RIGHT)
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "")
        self.button_2 = wx.Button(self, -1, "Select")
        self.button_3 = wx.Button(self, -1, "Go")
        self.fbbutton = fbb.FileBrowseButton(buttonText='Browse',
            dialogTitle='Select a file to save the results', fileMask='*.txt',
            labelText='File to save results:', parent=self,
            size=wx.Size(500, 35), style=wx.TAB_TRAVERSAL)


        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.hdlr_btn_select_1, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.hdlr_btn_select_2, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyBaseFrame.__set_properties
        self.SetTitle("Spots Distance Calculator")
        self.text_ctrl_1.SetMinSize((180, 29))
        self.text_ctrl_2.SetMinSize((180, 29))
        # end wxGlade

    def __do_layout(self):
        st_label = wx.LEFT|wx.RIGHT|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL
        st_txt_ctrl = wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL
        st_btn = wx.RIGHT|wx.ALIGN_CENTER_VERTICAL
        st_btn2 = wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL
        # begin wxGlade: MyBaseFrame.__do_layout
        grid_sizer_1 = wx.FlexGridSizer(3, 3, 2, 2)
        grid_sizer_1.Add(self.label_1, 0, st_label, 4)
        grid_sizer_1.Add(self.text_ctrl_1, 0, st_txt_ctrl, 0)
        grid_sizer_1.Add(self.button_1, 0, st_btn, 20)
        grid_sizer_1.Add(self.label_2, 0, st_label, 4)
        grid_sizer_1.Add(self.text_ctrl_2, 0, st_txt_ctrl, 0)
        grid_sizer_1.Add(self.button_2, 0, st_btn, 20)
        grid_sizer_1.Add((20, 0), 0, st_txt_ctrl, 0)
        grid_sizer_1.Add(self.fbbutton, 0, st_btn2, 10)
        grid_sizer_1.Add(self.button_3, 0, st_btn2, 10)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        grid_sizer_1.AddGrowableCol(1)
        self.SetBackgroundStyle(wx.BG_STYLE_SYSTEM)
        self.Layout()
        # end wxGlade

    def hdlr_btn_select_1(self, event): # wxGlade: MyBaseFrame.<event_handler>
        list_filter = 'Comma separated values (*.csv)|*.csv'
        fcd = FileChooser(wcd=list_filter)
        fname = fcd.get_path()
        if fname:
            self.text_ctrl_1.SetValue(fname)
        event.Skip()

    def hdlr_btn_select_2(self, event): # wxGlade: MyBaseFrame.<event_handler>
        list_filter = 'Xuv project file (*.xuv)|*.xuv'
        fcd = FileChooser(wcd=list_filter)
        fname = fcd.get_path()
        if fname:
            self.text_ctrl_2.SetValue(fname)
        event.Skip()

# end of class MyBaseFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyBaseFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
